const fs = require('fs');
const path = require('path');
const { PNG } = require('pngjs');
const { signatureBase64ToBuffer, signatureBase64ToDataUri } = require('./processSignatureImage');

/** Base64 payloads generated by scripts/generateEmbeddedAssets.js (committed for Vercel/serverless). */
let embeddedAssetsCache;

const tryRequireEmbedded = () => {
  try {
    // eslint-disable-next-line global-require, import/no-dynamic-require
    return require('../generated/embeddedAssets.cjs');
  } catch {
    try {
      // eslint-disable-next-line global-require, import/no-dynamic-require
      return require('../generated/embeddedAssets.json');
    } catch {
      return null;
    }
  }
};

const loadEmbeddedFromFsFallback = () => {
  const candidates = [
    path.join(__dirname, '../generated/embeddedAssets.json'),
    path.join(process.cwd(), 'src/generated/embeddedAssets.json'),
    path.join(process.cwd(), 'server/src/generated/embeddedAssets.json'),
    path.join(process.cwd(), 'backend/src/generated/embeddedAssets.json'),
    '/var/task/src/generated/embeddedAssets.json',
    path.join('/var/task/server/src/generated', 'embeddedAssets.json'),
    path.join('/var/task/backend/src/generated', 'embeddedAssets.json'),
  ];
  for (const p of candidates) {
    try {
      if (p && fs.existsSync(p)) {
        const raw = fs.readFileSync(p, 'utf8');
        const parsed = JSON.parse(raw);
        if (parsed && typeof parsed === 'object' && Object.keys(parsed).length > 0) return parsed;
      }
    } catch {
      /* next */
    }
  }
  return null;
};

const loadEmbeddedAssets = () => {
  if (embeddedAssetsCache !== undefined) return embeddedAssetsCache;

  let map = tryRequireEmbedded();
  if (!map || typeof map !== 'object' || !map['Md_SIGN.png']) {
    const fromFs = loadEmbeddedFromFsFallback();
    if (fromFs) map = fromFs;
  }
  embeddedAssetsCache = map && typeof map === 'object' ? map : {};

  if (process.env.VERCEL && !embeddedAssetsCache['Md_SIGN.png']) {
    console.error(
      '[PO] Embedded Md_SIGN missing on Vercel — run npm run generate:embedded-assets and commit src/generated/.',
    );
  }

  return embeddedAssetsCache;
};

const getEmbeddedBase64 = (filename) => {
  const key = String(filename || '').trim();
  if (!key) return '';
  const map = loadEmbeddedAssets();
  const v = map[key];
  return typeof v === 'string' && v.length > 0 ? v : '';
};

const tryRead = (absPath) => {
  try {
    if (!absPath) return null;
    if (!fs.existsSync(absPath)) return null;
    return fs.readFileSync(absPath);
  } catch {
    return null;
  }
};

let cachedAssetDirs = null;

const getAssetDirCandidates = () => {
  if (cachedAssetDirs) return cachedAssetDirs;

  const dirs = [];
  const add = (d) => {
    if (!d) return;
    const n = path.normalize(d);
    if (!dirs.includes(n)) dirs.push(n);
  };

  if (process.env.PO_ASSETS_DIR) add(process.env.PO_ASSETS_DIR);

  const cwd = process.cwd();
  add(path.join(cwd, 'assets'));
  add(path.join(cwd, 'server', 'assets'));
  add(path.join(cwd, 'backend', 'assets'));
  add(path.join('/var/task', 'assets'));
  add(path.join('/var/task', 'server', 'assets'));
  add(path.join('/var/task', 'backend', 'assets'));

  if (process.env.LAMBDA_TASK_ROOT) {
    add(path.join(process.env.LAMBDA_TASK_ROOT, 'assets'));
  }

  add(path.join(__dirname, '../../assets'));

  const mainFileDir = require.main?.filename ? path.dirname(require.main.filename) : '';
  if (mainFileDir) {
    add(path.join(mainFileDir, '../assets'));
    add(path.join(mainFileDir, '../../assets'));
  }

  cachedAssetDirs = dirs;
  return cachedAssetDirs;
};

const resolveAssetPath = (relativePath) => {
  const cleaned = String(relativePath || '').trim();
  if (!cleaned) return '';

  for (const dir of getAssetDirCandidates()) {
    const absPath = path.join(dir, cleaned);
    if (fs.existsSync(absPath)) return absPath;
  }
  return '';
};

const mimeFromFilename = (filename, fallbackMime) => {
  const ext = path.extname(filename).toLowerCase();
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  return fallbackMime;
};

const MD_SIGNATURE_STAMP = 'Md_SIGN.png';
let mdSignProcessedCache = null;
let mdSignCacheKey = '';

const transparentizeSignaturePng = (buffer) => {
  const png = PNG.sync.read(buffer);
  const threshold = 45;
  for (let i = 0; i < png.data.length; i += 4) {
    const r = png.data[i];
    const g = png.data[i + 1];
    const b = png.data[i + 2];
    if (r <= threshold && g <= threshold && b <= threshold) {
      png.data[i + 3] = 0;
    }
  }
  return PNG.sync.write(png);
};

const loadRawAssetBuffer = (relativePath) => {
  const cleaned = String(relativePath || '').trim();
  if (!cleaned) return null;

  const isServerless = Boolean(process.env.VERCEL || process.env.LAMBDA_TASK_ROOT);
  const diskPath = resolveAssetPath(cleaned);

  // In local/dev, prefer disk assets so replacing files is reflected immediately.
  if (!isServerless) {
    const disk = tryRead(diskPath);
    if (disk) return disk;
  }

  const embedded = getEmbeddedBase64(cleaned);
  if (embedded) {
    try {
      return Buffer.from(embedded, 'base64');
    } catch {
      return null;
    }
  }

  // In serverless, fallback to disk only if embedded asset is unavailable.
  return tryRead(diskPath);
};

const loadMdSignBuffer = () => {
  const isServerless = Boolean(process.env.VERCEL || process.env.LAMBDA_TASK_ROOT);
  const diskPath = resolveAssetPath(MD_SIGNATURE_STAMP);
  let cacheKey = isServerless ? 'serverless' : 'nodisk';

  if (!isServerless && diskPath) {
    try {
      const stats = fs.statSync(diskPath);
      cacheKey = `${diskPath}:${stats.mtimeMs}:${stats.size}`;
    } catch {
      cacheKey = `${diskPath}:stat-failed`;
    }
  }

  if (mdSignProcessedCache && mdSignCacheKey === cacheKey) return mdSignProcessedCache;

  const raw = loadRawAssetBuffer(MD_SIGNATURE_STAMP);
  if (!raw) return null;
  mdSignProcessedCache = transparentizeSignaturePng(raw);
  mdSignCacheKey = cacheKey;
  return mdSignProcessedCache;
};

const bufferToDataUri = (buffer, mime = 'image/png') => {
  if (!buffer) return '';
  return `data:${mime};base64,${buffer.toString('base64')}`;
};

const toDataUri = (relativePath, fallbackMime = 'image/jpeg') => {
  const cleaned = String(relativePath || '').trim();
  if (cleaned === MD_SIGNATURE_STAMP) {
    return bufferToDataUri(loadMdSignBuffer(), 'image/png');
  }

  const buffer = loadRawAssetBuffer(cleaned);
  if (!buffer) return '';

  const mime = mimeFromFilename(cleaned, fallbackMime);
  return bufferToDataUri(buffer, mime);
};

const readAssetBuffer = (relativePath) => {
  const cleaned = String(relativePath || '').trim();
  if (cleaned === MD_SIGNATURE_STAMP) return loadMdSignBuffer();
  return loadRawAssetBuffer(cleaned);
};

const loadAdminSignatureBuffer = (signatureImageBase64) => signatureBase64ToBuffer(signatureImageBase64);

const getAdminSignatureDataUri = (signatureImageBase64) => signatureBase64ToDataUri(signatureImageBase64);

const getMdSignatureDataUri = () => bufferToDataUri(loadMdSignBuffer(), 'image/png');

/** Logos + approver's uploaded signature + MD signature for PO PDF/Excel. */
const getPoDocumentAssets = ({ approverSignatureImage } = {}) => ({
  adminSignatureSrc: getAdminSignatureDataUri(approverSignatureImage),
  superadminSignatureSrc: getMdSignatureDataUri(),
});

/** Same as getPoDocumentAssets but returns raw Buffers — used by excelGenerator. */
const getPoDocumentAssetBuffers = ({ approverSignatureImage } = {}) => ({
  adminSignatureBuffer: loadAdminSignatureBuffer(approverSignatureImage),
  mdSignatureBuffer: loadMdSignBuffer(),
});

/**
 * Returns a @font-face CSS block with Roboto Regular + Bold embedded as base64
 * data URIs. Works in both local dev (reads from disk) and Vercel (reads from
 * embeddedAssets). Falls back to empty string so PDF generation never breaks.
 */
const readEmbeddedOrDisk = (filename) => {
  const b64 = getEmbeddedBase64(filename);
  if (b64) return b64;
  const p = resolveAssetPath(filename);
  if (p) try { return fs.readFileSync(p).toString('base64'); } catch { /* ignore */ }
  return '';
};

const getFontFaceCss = () => {
  const regularB64 = readEmbeddedOrDisk('Roboto-Regular.woff2');
  const boldB64 = readEmbeddedOrDisk('Roboto-Bold.woff2');
  // NotoSans subset covering Indian Rupee ₹ (U+20B9) and related currency/Devanagari chars
  const rupeeB64 = readEmbeddedOrDisk('NotoSans-Rupee.woff2');

  const blocks = [];
  if (regularB64) {
    blocks.push(`@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:url('data:font/woff2;base64,${regularB64}')format('woff2');}`);
  }
  if (boldB64) {
    blocks.push(`@font-face{font-family:'Roboto';font-style:normal;font-weight:700;src:url('data:font/woff2;base64,${boldB64}')format('woff2');}`);
  }
  if (rupeeB64) {
    // Scoped to only the unicode range that contains ₹ — avoids overriding Latin glyphs
    const rupeeRange = 'U+0900-097F,U+1CD0-1CF9,U+200C-200D,U+20A8,U+20B9,U+20F0,U+25CC,U+A830-A839,U+A8E0-A8FF';
    blocks.push(`@font-face{font-family:'Roboto';font-style:normal;font-weight:400;unicode-range:${rupeeRange};src:url('data:font/woff2;base64,${rupeeB64}')format('woff2');}`);
    blocks.push(`@font-face{font-family:'Roboto';font-style:normal;font-weight:700;unicode-range:${rupeeRange};src:url('data:font/woff2;base64,${rupeeB64}')format('woff2');}`);
  }
  return blocks.join('\n');
};

module.exports = {
  resolveAssetPath,
  toDataUri,
  readAssetBuffer,
  loadAdminSignatureBuffer,
  loadMdSignBuffer,
  getAdminSignatureDataUri,
  getMdSignatureDataUri,
  getPoDocumentAssets,
  getPoDocumentAssetBuffers,
  transparentizeSignaturePng,
  getFontFaceCss,
};
